openapi: 3.0.2

servers:
  - url: https://api.akso.org/v1
    description: Production server

info:
  title: AKSO's REST API
  version: 0.1.0
  description:
    Filterable properties are properties allowed in `?order` and `?filter` (collections only).


    Searchable properties are properties allowed in `?search` (collections only).


    All query parameters are allowed unless otherwise specified for a specific path.


    Fields marked as `string <markdown>` will be parsed using a CommonMark parser (like `markdown-it`), with only the rules mentioned in the field's description enabled + `newline`.


    All data obtained from the AKSO API is the intellectual property of UEA and/or TEJO unless the collection states a different license. Licenses applied to a certain endpoint are inherited by child endpoints unless overriden.

externalDocs:
  url: https://github.com/AksoEo/docs/tree/master/api
  description: Full documentation

