openapi: 3.0.2

servers:
  - url: https://api.akso.org/v1
    description: Production server

info:
  title: AKSO's REST API
  version: 0.1.0
  description:
    "This documentation uses the following custom properties:<br>

    - `x-queryable`:  (`boolean`, default: `false`) Whether the property may be queried using the `filter` or `order` query parameters.

    - `x-searchable`: (`boolean`, default: `false`) Whether the property may be queried using the `search` query parameter."

externalDocs:
  url: https://github.com/AksoEo/docs/tree/master/api
  description: Full documentation
