openapi: 3.0.2

servers:
  - url: https://api.akso.org/v1
    description: Production server

info:
  title: AKSO's REST API
  version: 0.1.0
  description:
    Filterable properties are properties allowed in `?order` and `?filter`.


    Searchable properties are properties allowed in `?search`.

externalDocs:
  url: https://github.com/AksoEo/docs/tree/master/api
  description: Full documentation
