#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

const header = fs.readFileSync(path.join(__dirname, 'spec/openapi.header.yaml'), 'utf-8');

const out = [];
out.push('paths:');
for (const item of fs.readdirSync(path.join(__dirname, 'spec/paths'))) {
    if (path.extname(item) === '.yaml') {
        const name = path.basename(item, '.yaml');
        const pathComponents = name.split('@');
        const pathname = '/' + pathComponents.join('/');
        out.push(`  '${pathname}':`);
        out.push(`    $ref: 'paths/${item}'`);
    }
}

const banner = `# note: this file is automatically generated\n`;
fs.writeFileSync(path.join(__dirname, 'spec/openapi.yaml'), banner + header + '\n' + out.join('\n'));
