#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

const header = fs.readFileSync(path.join(__dirname, 'spec/openapi.header.yaml'), 'utf-8');

const out = [];
out.push('paths:');
for (const item of fs.readdirSync(path.join(__dirname, 'spec/paths'))) {
    if (path.extname(item) === '.yaml') {
        const name = path.basename(item, '.yaml');
        const pathComponents = name.split('@');
        const pathname = '/' + pathComponents.join('/');
        out.push(`  '${pathname}':`);
        out.push(`    $ref: 'paths/${item}'`);
    }
}

out.push('components:');
out.push('  schemas:');

const handleDir = (dir) => {
    for (const item of fs.readdirSync(path.join(__dirname, dir))) {
        if (path.extname(item) === '.yaml') {
            const name = path.basename(item, '.yaml');
            out.push(`    '${name}':`);
            out.push(`      $ref: '${path.join(dir, item)}'`);
        } else if (fs.statSync(path.join(__dirname, dir, item)).isDirectory()) {
            handleDir(path.join(dir, item));
        }
    }
};
handleDir('spec/components');

const banner = `# note: this file is automatically generated\n`;
fs.writeFileSync(path.join(__dirname, 'spec/openapi.yaml'), banner + header + '\n' + out.join('\n'));
