parameters:
  - name: applicationId
    in: path
    required: true
    description: The id of the application
    schema:
      type: integer
      format: uint32

get:
  summary: Gets a delegation application
  description: >
    Requires permission: `codeholders.read`, `delegations.applications.read.<org>`
  responses:
    '404':
      description: Not found
    '200':
      description: OK
      content:
        application/vnd.msgpack:
          schema:
            $ref: '../components/schemas/DelegationApplication.yaml'

patch:
  summary: Updates a delegation application
  description: >
    Requires permission: `codeholders.read`, `delegations.applications.update.<org>`
  requestBody:
    required: true
    content:
      application/vnd.msgpack:
        schema:
          allOf:
            - properties:
                org:
                  readOnly: true
                codeholderId:
                  readOnly: true
                cities:
                  readOnly: true
                subjects:
                  readOnly: true
                hosting:
                  readOnly: true
                tos:
                  readOnly: true
            - $ref: '../components/schemas/DelegationApplication.yaml'
  responses:
    '204':
      description: Updated
    '404':
      description: Not found

delete:
  summary: Deletes a delegation application
  description: >
    Requires permission: `codeholders.read`, `delegations.applications.delete.<org>`
  responses:
    '204':
      description: Deleted
    '404':
      description: Not found
